const citiesData = [
  {
    name: 'Abu Dhabi',
    lat: 24.46,
    lon: 54.36,
    country: 'UAE',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/us/us/512.png',
    backgroundImageUrl: '../assets/abu-dhabi.jpg',
  },
  {
    name: 'Amsterdam',
    lat: 52.37,
    lon: 4.88,
    country: 'Netherlands',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/us/us/512.png',
    backgroundImageUrl: '../assets/amsterdam.jpeg',
  },
  {
    name: 'Bangkok',
    lat: 13.75,
    lon: 100.51,
    country: 'Thailand',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/us/us/512.png',
    backgroundImageUrl: '../assets/bangkok.jpeg',
  },
  {
    name: 'Beijing',
    lat: 39.90,
    lon: 116.39,
    country: 'China',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/asia/cn/512.png',
    backgroundImageUrl: '../assets/beijing.jpeg',
  },
  {
    name: 'Berlin',
    lat: 52.51,
    lon: 13.38,
    country: 'Germany',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/de/512.png',
    backgroundImageUrl: '../assets/berlin.jpeg',
  },
  {
    name: 'Cairo',
    lat: 30.06,
    lon: 31.24,
    country: 'Egypt',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/us/us/512.png',
    backgroundImageUrl: '../assets/cairo.jpeg',
  },
  {
    name: 'Hong Kong',
    lat: 22.28,
    lon: 114.15,
    country: 'China',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/us/us/512.png',
    backgroundImageUrl: '../assets/HongKong.jpg',
  },
  {
    name: 'London',
    lat: 44.34,
    lon: 10.99,
    country: 'UK',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/gb/512.png',
    backgroundImageUrl: '../assets/London.jpg',
  },
  {
    name: 'Moscow',
    lat: 55.75,
    lon: 37.61,
    country: 'Russia',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/us/us/512.png',
    backgroundImageUrl: '../assets/moscow.jpg',
  },
  {
    name: 'Mumbai',
    lat: 19.07,
    lon: 72.87,
    country: 'India',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/asia/in/512.png',
    backgroundImageUrl: '../assets/mumbai.jpeg',
  },
  {
    name: 'New York',
    lat: 39.68,
    lon: -93.92,
    country: 'USA',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/us/us/512.png',
    backgroundImageUrl: '../assets/newYork.jpeg',
  },
  {
    name: 'Paris',
    lat: 48.85,
    lon: 2.32,
    country: 'France',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/fr/512.png',
    backgroundImageUrl: '../assets/paris.jpeg',
  },
  {
    name: 'Rio De Janeiro',
    lat: 38.3,
    lon: 21.78,
    country: 'Brazil',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/us/us/512.png',
    backgroundImageUrl: '../assets/Rio.jpeg',
  },
  {
    name: 'Rome',
    lat: 41.89,
    lon: 12.48,
    country: 'Italy',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/gr/512.png',
    backgroundImageUrl: '../assets/romee.jpeg',
  },
  {
    name: 'Seoul',
    lat: 37.56,
    lon: 126.97,
    country: 'South Korea',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/us/us/512.png',
    backgroundImageUrl: '../assets/seoul.jpeg',
  },
  {
    name: 'Singapore',
    lat: 1.28,
    lon: 103.85,
    country: 'Singapore',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/asia/sg/512.png',
    backgroundImageUrl: '../assets/singapore.jpg',
  },
  {
    name: 'Spain',
    lat: 40.41,
    lon: -3.70,
    country: 'Spain',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/es/512.png',
    backgroundImageUrl: '../assets/spainn.jpg',
  },
  {
    name: 'Stockholm',
    lat: 59.33,
    lon: 18.05,
    country: 'Sweden',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/us/us/512.png',
    backgroundImageUrl: '../assets/stockholm.jpeg',
  },
  {
    name: 'Tokyo',
    lat: 35.67,
    lon: 139.76,
    country: 'Japan',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/asia/jp/512.png',
    backgroundImageUrl: '../assets/tokyo.jpeg',
  },
  {
    name: 'Yangon',
    lat: 16.80,
    lon: 96.15,
    country: 'Myanmar',
    img: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/gb/512.png',
    backgroundImageUrl: '../assets/yangon.jpg',
  },
];

export default citiesData;
